# service.yaml
kind: Service
apiVersion: v1
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
    - name: http
      port: 80 
      nodePort:
        30080 
  type: NodePort 